headhunter/headhunter/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('auth/', include('accounts.urls')),
    path('resume/', include('resume.urls')),
    path('vacancies/', include('vacancies.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

headhunter/resume/urls.py
from django.urls import path
from .views import ResumeCreateView, ResumeEditView, ResumeDetailView, EducationCreateView, ExperienceCreateView

urlpatterns = [
    path('create/', ResumeCreateView.as_view(), name='resume_create'),
    path('<int:pk>/edit/', ResumeEditView.as_view(), name='resume_edit'),
    path('<int:pk>/detail/', ResumeDetailView.as_view(), name='resume_detail'),
    path('<int:pk>/create/experience/', ExperienceCreateView.as_view(), name='resume_experience_create'),
    path('<int:pk>/create/education/', EducationCreateView.as_view(), name='resume_education_create')
]

headhunter/vacancies/urls.py
from django.urls import path

from vacancies.views import VacancyCreateView, VacancyListView, VacancyEditView, VacancyDetailView, ResponceToVacancy

urlpatterns = [
    path('', VacancyListView.as_view(), name='vacancies'),
    path('create/', VacancyCreateView.as_view(), name='vacancy_create'),
    path('<int:pk>/edit/', VacancyEditView.as_view(), name='vacancy_edit'),
    path('<int:pk>/detail/', VacancyDetailView.as_view(), name='vacancy_detail'),
    path('<int:pk>/respose/', ResponceToVacancy.as_view(), name='response_to_vacancy')
]

headhunter/vacancies/models/vacancies.py
from django.contrib.auth import get_user_model
from django.db import models

from resume.models.resumes import ProfessionChoices


class Vacancy(models.Model):
    author = models.ForeignKey(to=get_user_model(), verbose_name='Работодатель', related_name='author_vacancy', null=False, blank=False, on_delete=models.CASCADE)
    title = models.CharField(verbose_name='Вакансия', max_length=100, null=False, blank=False)
    salary = models.DecimalField(verbose_name='Заработная плата', max_digits=12, decimal_places=2, null=False, blank=False)
    description = models.TextField(verbose_name='Описание вакансии', null=True)
    profession = models.CharField(verbose_name='Сфера деятельности', max_length=30, null=False, blank=False, choices=ProfessionChoices.choices)
    experience_from = models.DecimalField(verbose_name='Стаж от', max_digits=10, decimal_places=2, null=False, blank=False)
    experience_before = models.DecimalField(verbose_name='Стаж до', max_digits=10, decimal_places=2, null=False, blank=False)
    created_at = models.DateTimeField(verbose_name='Дата создания', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='Дата редактирования', auto_now=True)

class ResponseToVacancy(models.Model):
    author = models.ForeignKey(to=get_user_model(), verbose_name='Отклик пользователя', related_name='responces_to_vacancy', null=False, blank=False, on_delete=models.CASCADE)
    resume = models.ForeignKey(verbose_name='Резюме', to='resume.Resume', related_name='responces_to_vacancy', null=False, blank=False, on_delete=models.CASCADE)
    vacancy = models.ForeignKey(to='Vacancy', verbose_name='Вакансия', related_name='responces_to_vacancy', null=False, blank=False, on_delete=models.CASCADE)

headhunter/vacancies/forms.py
from django import forms
from resume.models import Resume
from vacancies.models.vacancies import Vacancy, ResponseToVacancy


class VacancyForm(forms.ModelForm):

    class Meta:
        model = Vacancy
        fields = ('title', 'salary', 'description', 'profession', 'experience_from', 'experience_before')


class VacancyResponceForm(forms.ModelForm):
    def __init__(self, current_user, *args, **kwargs):
        super(VacancyResponceForm, self).__init__(*args, **kwargs)
        self.fields['resume'].queryset = self.fields['resume'].queryset.filter(author=current_user.pk)

    resume = forms.ModelChoiceField(
        label='Необходимо выбрать резюме',
        queryset=Resume.objects.all(),
    )
    class Meta:
        model = ResponseToVacancy
        fields = ('resume', )


class SearchForm(forms.Form):
    search = forms.CharField(max_length=100, required=False, label='')

headhunter/vacancies/views.py
from django.shortcuts import redirect
from django.views.generic import CreateView, ListView, UpdateView, DetailView
from django.urls import reverse
from vacancies.forms import VacancyForm, SearchForm, VacancyResponceForm
from vacancies.models.vacancies import Vacancy, ResponseToVacancy
from django.http import HttpResponse



class VacancyListView(ListView):
    template_name = 'vacancies.html'
    model = Vacancy
    context_object_name = 'vacancies'

    def get(self, request, *args, **kwargs):
        self.form = SearchForm(self.request.GET)
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data.get('search')
        return None

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            queryset = Vacancy.objects.filter(title__icontains=self.search_value)
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data()
        context['form'] = self.form
        return context


class VacancyCreateView(CreateView):
    template_name = 'vacancies_create.html'
    form_class = VacancyForm
    model = Vacancy

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            form.instance.author_id = request.user.pk
            form.save()
            return redirect('user_detail', pk=request.user.pk)
        context = {}
        context['form'] = form
        return self.render_to_response(context)

    def get_success_url(self, request):
        return reverse('user_detail', pk=request.user.pk)


class VacancyEditView(UpdateView):
    template_name = 'vacancies_edit.html'
    form_class = VacancyForm
    model = Vacancy
    context_object_name = 'vacancy'

    def get_context_data(self, **kwargs):
        context = super(VacancyEditView, self).get_context_data(**kwargs)
        context['form'] = VacancyForm(instance=self.object)
        return context

    def get_success_url(self):
        return reverse('vacancy_detail', kwargs={'pk': self.object.pk})


class VacancyDetailView(DetailView):
    template_name = 'vacancies_detail.html'
    model = Vacancy
    context_object_name = 'vacancy'


class ResponceToVacancy(CreateView):
    model = ResponseToVacancy
    form_class = VacancyResponceForm

    def post(self, request, *args, **kwargs):
        vacancy = Vacancy.objects.get(pk=kwargs['pk'])
        author = request.user
        resume = request.POST['resume']
        ResponseToVacancy.objects.create(author=author, resume_id=resume, vacancy=vacancy)
        return HttpResponse(status=201)

    def get_context_data(self, request, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        form = self.form_class
        context['form'] = form
        return context

headhunter/vacancies/templates/partial/card_vacancy.html
<div class="container px-4 py-5" id="featured-3">
    <h3 class="pb-2 border-bottom">{{el.title}}</h3>
      <div class="feature col">
        <h4>{{el.get_profession_display}}</h4>
        <p >{{el.salary}}</p>
         <p>{{ el.updated_at }}</p>
        <a href="" class="btn btn-outline-secondary btn-lg" type="button">Обновить</a>
        <a href=" {% url 'vacancy_edit' el.pk %} " class="btn btn-outline-secondary btn-lg" type="button">Редактировать</a>
      </div>
    </div>
  </div>
<div class="b-example-divider"></div>

headhunter/vacancies/templates/partial/search.html
{% load django_bootstrap5 %}
{% load static %}
<form class="text-center" action="" method="GET">
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content='Поиск' %}
</form>

headhunter/vacancies/templates/partial/vacancies_form.html
{% load django_bootstrap5 %}

{% bootstrap_form form %}

headhunter/vacancies/templates/partial/vacancy_responce_form.html
{% load django_bootstrap5 %}

<div class="modal fade" id="vacancy_add_responce" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Необходимо выбрать резюме</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div id="alert" class="alert alert-danger d-none" role="alert"></div>
          <form action="{% url 'login' %}" method="POST" enctype="multipart/form-data">
              <div class="modal-body">
                {% csrf_token %}
                <div class="form">
                    {% bootstrap_form form %}
                </div>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
                <button type="submit" id="submit" class="btn btn-primary">Выбрать</button>
              </div>
          </form>
        </div>
      </div>
    </div>